// Tech Stack - distinct logos verified via Google / Simple Icons / Devicons / Brand favicons
export const techCategories = [
  {
    label: "Frontend & UI",
    sub: "Modern interfaces, animations & design systems",
    items: [
      { name: "HTML5", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" },
      { name: "CSS3", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" },
      { name: "JavaScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" },
      { name: "React", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
      { name: "React Router", icon: "https://cdn.simpleicons.org/reactrouter/CA4245" },
      { name: "Next.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg" },
      { name: "Tailwind CSS", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg" },
      { name: "Redux", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg" },
      { name: "Recoil", icon: "https://cdn.simpleicons.org/recoil/3578E5" },
      { name: "TanStack Query", icon: "https://cdn.simpleicons.org/tanstack/FF4154" },
      { name: "Axios", icon: "https://cdn.simpleicons.org/axios/5A29E4" },
      { name: "Framer Motion", icon: "https://cdn.simpleicons.org/framer/0055FF" },
      { name: "GSAP", icon: "https://cdn.simpleicons.org/greensock/88CE02" },
      { name: "Lenis", icon: "https://www.google.com/s2/favicons?domain=lenis.darkroom.engineering&sz=64" },
      { name: "MUI", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/materialui/materialui-original.svg" },
      { name: "Ant Design", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/antdesign/antdesign-original.svg" },
      { name: "shadcn/ui", icon: "https://cdn.simpleicons.org/shadcnui/000000" },
      { name: "HeroUI", icon: "https://www.google.com/s2/favicons?domain=heroui.com&sz=64" },
      { name: "Mantine UI", icon: "https://cdn.simpleicons.org/mantine/339AF0" },
      { name: "React Aria", icon: "https://www.google.com/s2/favicons?domain=react-spectrum.adobe.com&sz=64" },
      { name: "Radix UI", icon: "https://cdn.simpleicons.org/radixui/161618" },
      { name: "Base UI", icon: "https://cdn.simpleicons.org/baseui/000000" },
      { name: "Reshaped", icon: "https://www.google.com/s2/favicons?domain=reshaped.so&sz=64" },
      { name: "daisyUI", icon: "https://cdn.simpleicons.org/daisyui/1AD0FF" },
      { name: "Kibo UI", icon: "https://www.google.com/s2/favicons?domain=kibo-ui.com&sz=64" },
      { name: "AlignUI", icon: "https://www.google.com/s2/favicons?domain=alignui.com&sz=64" },
      { name: "Tailark", icon: "https://www.google.com/s2/favicons?domain=tailark.com&sz=64" },
      { name: "Lightwind UI", icon: "https://codewithmuhilan.com/Extra-Assets/lightwind-logo.png" },
      { name: "ReactBits", icon: "https://www.google.com/s2/favicons?domain=reactbits.dev&sz=64" },
      { name: "Floating UI", icon: "https://www.google.com/s2/favicons?domain=floating-ui.com&sz=64" },
      { name: "Electron.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/electron/electron-original.svg" },
      { name: "Capacitor", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/capacitor/capacitor-plain.svg" },
      { name: "React Native", icon: "https://cdn.simpleicons.org/expo/000020" },
    ],
  },
  {
    label: "Backend & Databases",
    sub: "Scalable APIs, authentication & data management",
    items: [
      { name: "Node.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg" },
      { name: "Express.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg" },
      { name: "Python", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg" },
      { name: "REST API", icon: "https://www.google.com/s2/favicons?domain=openapis.org&sz=64" },
      { name: "JWT", icon: "https://cdn.simpleicons.org/jsonwebtokens/000000" },
      { name: "Socket.IO", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/socketio/socketio-original.svg" },
      { name: "WebRTC", icon: "https://cdn.simpleicons.org/webrtc/333333" },
      { name: "Multer", icon: "https://www.google.com/s2/favicons?domain=github.com&sz=64" },
      { name: "Nodemailer", icon: "https://www.google.com/s2/favicons?domain=nodemailer.com&sz=64" },
      { name: "PDFKit", icon: "https://www.google.com/s2/favicons?domain=pdfkit.org&sz=64" },
      { name: "MongoDB", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg" },
      { name: "PostgreSQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg" },
      { name: "MySQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg" },
      { name: "Redis", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg" },
      { name: "Kafka", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachekafka/apachekafka-original.svg" },
      { name: "DynamoDB", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dynamodb/dynamodb-original.svg" },
      { name: "NeonDB", icon: "https://cdn.simpleicons.org/neon/00E699" },
    ],
  },
  {
    label: "Cloud, DevOps & Deployment",
    sub: "Deployment, hosting & production infrastructure",
    items: [
      { name: "Git", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg" },
      { name: "GitHub", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" },
      { name: "GitHub Actions", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/githubactions/githubactions-original.svg" },
      { name: "Docker", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg" },
      { name: "Nginx", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nginx/nginx-original.svg" },
      { name: "AWS", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original-wordmark.svg" },
      { name: "Google Cloud", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg" },
      { name: "Vercel", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vercel/vercel-original.svg" },
      { name: "Render", icon: "https://cdn.simpleicons.org/render/46E3B7" },
      { name: "Serverless", icon: "https://cdn.simpleicons.org/serverless/FD5750" },
      { name: "VPS", icon: "https://www.google.com/s2/favicons?domain=digitalocean.com&sz=64" },
      { name: "Hostinger", icon: "https://cdn.simpleicons.org/hostinger/673DE8" },
      { name: "GoDaddy", icon: "https://cdn.simpleicons.org/godaddy/1BDBDB" },
      { name: "EC2", icon: "https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=64" },
      { name: "Netlify", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/netlify/netlify-original.svg" },
      { name: "Shopify", icon: "https://cdn.simpleicons.org/shopify/7AB55C" },
      { name: "Playwright", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/playwright/playwright-original.svg" },
    ],
  },
  {
    label: "Services & Integrations",
    sub: "Authentication, storage, payments & third-party services",
    items: [
      { name: "Auth0", icon: "https://cdn.simpleicons.org/auth0/EB5421" },
      { name: "Firebase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg" },
      { name: "Supabase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/supabase/supabase-original.svg" },
      { name: "Clerk", icon: "https://cdn.simpleicons.org/clerk/6C47FF" },
      { name: "Brevo", icon: "https://cdn.simpleicons.org/brevo/0B9964" },
      { name: "SendGrid", icon: "https://www.google.com/s2/favicons?domain=sendgrid.com&sz=64" },
      { name: "Razorpay", icon: "https://cdn.simpleicons.org/razorpay/02042B" },
      { name: "Cashfree", icon: "https://www.google.com/s2/favicons?domain=cashfree.com&sz=64" },
      { name: "Cloudinary", icon: "https://cdn.simpleicons.org/cloudinary/3448C5" },
      { name: "FlexSearch", icon: "https://www.google.com/s2/favicons?domain=github.com&sz=64" },
      { name: "React Charts", icon: "https://www.google.com/s2/favicons?domain=recharts.org&sz=64" },
      { name: "MapCN", icon: "https://www.google.com/s2/favicons?domain=mapbox.com&sz=64" },
      { name: "VS Code", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg" },
      { name: "Postman", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postman/postman-original.svg" },
      { name: "Excel", icon: "https://www.google.com/s2/favicons?domain=microsoft.com&sz=64" },
      { name: "C++", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg" },
      { name: "Calendly", icon: "https://cdn.simpleicons.org/calendly/006BFF" },
      { name: "Stripe", icon: "https://cdn.simpleicons.org/stripe/635BFF" },
      { name: "Figma", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg" },
      { name: "Linear", icon: "https://cdn.simpleicons.org/linear/5E6AD2" },
      { name: "PostHog", icon: "https://cdn.simpleicons.org/posthog/000000" },
    ],
  },
  {
    label: "AI, ML & Data",
    sub: "Intelligent systems, models & visualizations",
    items: [
      { name: "OpenAI", icon: "https://cdn.simpleicons.org/openai/412991" },
      { name: "Anthropic", icon: "https://cdn.simpleicons.org/anthropic/D97757" },
      { name: "Hugging Face", icon: "https://cdn.simpleicons.org/huggingface/FFD21E" },
      { name: "Pandas", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg" },
      { name: "Numpy", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/numpy/numpy-original.svg" },
      { name: "Scikit-learn", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/scikitlearn/scikitlearn-original.svg" },
      { name: "PyTorch", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg" },
      { name: "TensorFlow", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg" },
      { name: "LangChain", icon: "https://cdn.simpleicons.org/langchain/1C3C3C" },
      { name: "LangGraph", icon: "https://cdn.simpleicons.org/langgraph/000000" },
      { name: "Vector DB", icon: "https://www.google.com/s2/favicons?domain=pinecone.io&sz=64" },
      { name: "Random Forest", icon: "https://cdn.simpleicons.org/scikitlearn/F7931E" },
      { name: "K-Means", icon: "https://www.google.com/s2/favicons?domain=scikit-learn.org&sz=64" },
      { name: "Matplotlib", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/matplotlib/matplotlib-original.svg" },
      { name: "Seaborn", icon: "https://www.google.com/s2/favicons?domain=seaborn.pydata.org&sz=64" },
    ],
  },
  {
    label: "Languages & Frameworks",
    sub: "Core languages and runtime platforms",
    items: [
      { name: "TypeScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg" },
      { name: "Vue.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg" },
      { name: "Svelte", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg" },
      { name: "Vite", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vitejs/vitejs-original.svg" },
      { name: "Bun", icon: "https://cdn.simpleicons.org/bun/000000" },
      { name: "GraphQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg" },
      { name: "Prisma", icon: "https://cdn.simpleicons.org/prisma/2D3748" },
      { name: "Drizzle", icon: "https://cdn.simpleicons.org/drizzle/C5F74F" },
      { name: "Flutter", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg" },
      { name: "Kotlin", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg" },
      { name: "Swift", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg" },
      { name: "Rust", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-plain.svg" },
      { name: "Go", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg" },
      { name: "Kubernetes", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg" },
      { name: "Cloudflare", icon: "https://cdn.simpleicons.org/cloudflare/F38020" },
    ],
  },
];

export const allTechs = techCategories.flatMap(c => c.items);
export function getReelRows(rows = 7) {
  const perRow = Math.ceil(allTechs.length / rows) + 4;
  const result = [];
  for (let r = 0; r < rows; r++) {
    const offset = (r * 11) % allTechs.length;
    const slice = [];
    for (let i = 0; i < perRow + 6; i++) slice.push(allTechs[(offset + i) % allTechs.length]);
    result.push(slice);
  }
  return result;
}
